### PR TITLE
docs: add link to langfuse in LangfuseConnector

### PR DESCRIPTION
**Pull request by marcklingen**
### Related Issues

None

### Proposed Changes:

I propose to add a link to Langfuse to help people figure out what Langfuse actually is when browsing the api reference.

### How did you test it?

I did not test it

### Notes for the reviewer

None

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

### CODE REVIEW

**Comment by marcklingen** [comment]
@vblagoje What do you think? I saw a link when checking out the chroma integration api reference and thought it would be useful on the langfuse page as well.

**Comment by vblagoje** [comment]
Sounds good @marcklingen ! A small ask from our side is to add "Usage Notice" from https://docs.haystack.deepset.ai/docs/langfuseconnector somewhere in your https://langfuse.com/docs/integrations/haystack/get-started page as well. We had some users accidentally import one of the Haystack components before setting tracing enabled, leading to improper initialization ultimately resulting in no logs showing up in Langfuse. It's a common mistake our users face, see:

- https://github.com/deepset-ai/haystack/issues/8126
- https://github.com/deepset-ai/haystack-core-integrations/issues/789

**Comment by marcklingen** [comment]
Got this feedback as well and added a note here: https://langfuse.com/docs/integrations/haystack/get-started#set-environment-variables

**Review by vblagoje — APPROVED** [review]
Thanks for this update @marcklingen

**Pull request merged**
