### PR TITLE
chore: Update Anthropic example, use ChatPromptBuilder properly

### PR DESCRIPTION
**Pull request by vblagoje**
- Properly use ChatPromptBuilder init with documents variable
- Inject document content into prompt not just str of the document
- Verify component connections
- Verify output is based on fetched document

### CODE REVIEW

**Comment by vblagoje** [comment]
@Amnah199 David and I talked about this example yesterday and how it needs an update. This is that update 😄

**Review by davidsbatista — APPROVED** [review]
I see now, `ChatPrompBuilder` changed

**Comment by davidsbatista** [comment]
@vblagoje the docs also need to be updated: https://haystack.deepset.ai/integrations/anthropic#haystack-20

**Comment by vblagoje** [comment]
Thank you for this @davidsbatista https://github.com/deepset-ai/haystack-integrations/pull/254 
All other docs are ok, merging this one

**Pull request merged**
