### PR TITLE
Adding support for Supabase vector store

### PR DESCRIPTION
**Pull request by sahusiddharth**
- fixes: #73

- Vecs Python Client Integration: The pull request includes the incorporation of the Supabase Vecs Python client into the Haystack codebase.
- Support for Supabase Vector Store: Code modifications have been made to enable Haystack to interact with and utilize the capabilities of the Supabase Vector Store.

### CODE REVIEW

**Comment by sahusiddharth** [comment]
@julian-risch 

Can you help me with writing a the test cases. 
Let me know changes that needs to be made in this.

**Comment by julian-risch** [comment]
Hello @sahusiddharth thank you for opening this PR! 🎉 Regarding the tests, we need `test_document_store.py` and `test_embedding_retriever.py`. You can have a look at the implementation of the tests in other document store integrations, for example https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/elasticsearch/tests/test_document_store.py and https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/elasticsearch/tests/test_embedding_retriever.py .
When you inherit from `DocumentStoreBaseTests` as it is done here, some tests will automatically be provided: https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/elasticsearch/tests/test_document_store.py#L19C1-L19C49 
By defining a fixture as it is done here you can use an instance of the document store in your tests: https://github.com/deepset-ai/haystack-core-integrations/blob/8aede9cecc43790ed80934db7e9bcad3a1aadc37/integrations/elasticsearch/tests/test_document_store.py#L26
As you have probably already found out through the [document page](https://docs.haystack.deepset.ai/v2.0/docs/creating-custom-document-stores) while working on the Supabase document store, we have a blueprint version of a document store and the tests here: https://github.com/deepset-ai/document-store/blob/main/tests/test_document_store.py
I hope these links are helpful to you. Please just let me know if you have any questions or need more support!

**Comment by sahusiddharth** [comment]
@julian-risch supabase is kinda similar to pinecone because we need user password host and port to connect, I tried taking reference from  Pinecone on how it is connecting to the index, but I was not able to figure it out, can you give some suggestions on how can I do this?

**Comment by julian-risch** [comment]
@sahusiddharth Ideally, we should return the number of documents written, yes. If you don't see a way to do that no worries. We can also focus on all other functionalities first and add this feature in a separate PR if it is complicated to implement.

**Pull request closed without merging**
