### PR TITLE
Langfuse: add invocation_context to identify traces

### PR DESCRIPTION
**Pull request by vblagoje**
- WIP, used to demonstrate a possible solution to https://github.com/deepset-ai/haystack-core-integrations/issues/916

### CODE REVIEW

**Comment by ggdupont** [comment]
Any estimate on when this could be merged?

**Comment by ggdupont** [comment]
> Do you find this PR useful @ggdupont ? Can you tell us a bit about your use case please?

I want (at least) to track session id accross calls to the llm just like the original [issue](https://github.com/deepset-ai/haystack-core-integrations/issues/916). Later I also plan to add conversation metrics for performance monitoring. All should be ligh weigths and simple type metadata so the "invocation_context" seems quite perfect for this.

**Comment by vblagoje** [comment]
Ok thank you @ggdupont I agree and it seems like a low impact high return PR. Let's see what the peer review says

**Comment by vblagoje** [comment]
@silvanocerza please have a look as well and luk your thoughts.

**Comment by vblagoje** [comment]
ping @silvanocerza - have a look now 🙏

**Review by silvanocerza — APPROVED** [review]

**Comment by ggdupont** [comment]
FYI already integrated and happy of the result.

**Pull request merged**
