### PR TITLE
fix: make "project-id" parameter optional during initialization

### LINKED ISSUE #1130: bug: google-vertex-ai forces you to specify the project_id as a parameter
When using the VertexAIGeminiGenerator, I believe it this piece of code here should run without issues, assuming that the `GCP_PROJECT_ID` and `GOOGLE_APPLICATION_CREDENTIALS` are also set:

```python
from haystack_integrations.components.generators.google_vertex import VertexAIGeminiGenerator

gemini = VertexAIGeminiGenerator()
result = gemini.run(parts = ["What is the most interesting thing you know?"])
for answer in result["replies"]:
    print(answer)
```

However, requiring project_id as a parameter hinders our ability to create a multi-LLM service abstraction that leverages various Haystack generators. We aim for generator-agnostic implementation to test and use the best performers.

As you can see in my console the variables are indeed set

image

### PR DESCRIPTION
**Pull request by Amnah199**
### Related Issues

- fixes #1130 

### Proposed Changes:

The `project` is automatically set during authentication using Google Cloud ADCs, which is required for configuration. Therefore, we can make the `project-id` optional in the component `init`.

### How did you test it?

- Ran existing tests
- Manual testing using examples

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

### CODE REVIEW

**Review by julian-risch — CHANGES_REQUESTED** [review]
Looks quite good to me! I suggest that we remove the `project_id` param from the initialization of the VertexAIGeminiChatGenerator too. Other than that ready to be merged.

I checked what error message we get if no project id is provided at all.
```
    raise GoogleAuthError(project_not_found_exception_str) from exc
google.auth.exceptions.GoogleAuthError: Unable to find your project. Please provide a project ID by:
- Passing a constructor argument
- Using vertexai.init()
- Setting project using 'gcloud config set project my-project'
- Setting a GCP environment variable
- To create a Google Cloud project, please follow guidance at https://developers.google.com/workspace/guides/create-project
```
Looks good.

**Review by julian-risch — CHANGES_REQUESTED** [review]
One more change request: let's remove `project_id` from the `test_to_dict` and `test_from_dict`. We can keep it in `test_to_dict_with_params` and `test_from_dict_with_param`.

**Comment by Amnah199** [comment]
`VertexAIGeminiChatGenerator` is already updated. I'll update the tests too 👍

**Comment by Amnah199** [comment]
@julian-risch updated the examples and also removed `project_id` from all tests except `init`. Let me know WDYT.

**Review by julian-risch — APPROVED** [review]
LGTM! 👍

**Pull request merged**
