### PR TITLE
refactor: change meta data fields

### PR DESCRIPTION
**Pull request by davidsbatista**
### Related Issues

- fixes [#7687](https://github.com/deepset-ai/haystack/issues/7687)

### Proposed Changes:

- rewrite the keys in the `meta` field from each `ChatMessage` before returning the `List[ChatMessage]`

### How did you test it?

- unit tests, integration tests, manual verification

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

### CODE REVIEW

**Comment by shadeMe** [comment]
This is blocked until we get a new release of both core integrations out there with the deprecation, right? We don't have a strict deprecation policy for the core integrations, but I think we can park this until the 2.4 Haystack release and push out new patch versions with deprecations now.

**Comment by davidsbatista** [comment]
the release was already made yesterday

**Comment by davidsbatista** [comment]
> we can park this until the 2.4 Haystack release and push out new patch versions with deprecations now.
they are unrelated, don't depende on each other

**Comment by shadeMe** [comment]
> > we can park this until the 2.4 Haystack release and push out new patch versions with deprecations now.
> 
> they are unrelated, don't depende on each other

Sure, but it's still a breaking change for the users of the above core integrations. It makes sense to wait a bit before we merge the changes (we just pushed out the deprecation warnings after all).

**Review by anakin87 — APPROVED** [review]
Looks good.

- please rename this PR so that it is descriptive and respects our convention. Keep in mind that PR titles in core-integrations are used to populate the CHANGELOG.md.
- since this is a breaking change, after merging, we should release a major version of each package involved.

**Pull request merged**
