### PR TITLE
feat: made truncation optional for BedrockGenerator

### LINKED ISSUE #783: Amazon Bedrock Generators missing `kwargs` init params when serializing
**Describe the bug**
The Amazon Bedrock Generators init method allows for `kwargs`
https://github.com/deepset-ai/haystack-core-integrations/blob/6aaf523636d923ce158c46ea39a057f5529b5a17/integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py#L65-L77

but in the `to_dict` method ignores these kwargs

https://github.com/deepset-ai/haystack-core-integrations/blob/6aaf523636d923ce158c46ea39a057f5529b5a17/integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py#L251-L267

which means serializing and then deserializing will result in a different Generator with different behavior (e.g. if a user sets the `temperature` as a `kwarg` then this value will be "forgotten").

**To Reproduce**
Serialize a Bedrock generator using a `kwarg` and then deserialize.

**Describe your environment (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Haystack version: 2.2
 - Integration version: 0.8.0

### LINKED ISSUE #785: Make truncation optional for AmazonBedrockGenerators
**Is your feature request related to a problem? Please describe.**
We've found that in some situations we'd prefer the model provider (e.g. Bedrock) to return with an error message if the prompt is too long rather than truncate the end of the prompt which can lead to non-sensical answers depending on how the prompt template is constructed. So I propose adding a parameter to toggle this behavior with the default behavior being unchanged (i.e. truncation=True is the same as the previous default behavior).

**Describe the solution you'd like**
Similar solution as was implemented in this [PR](https://github.com/deepset-ai/haystack/pull/7431) for Haystack v1.

### PR DESCRIPTION
**Pull request by Amnah199**
### Related Issues

- fixes #785 
- fixes #783 

### Proposed Changes:

- Added 'truncate' parameter to initialization method. 
- Added kwargs in serialization method

### How did you test it?

Updated unit tests
 Integration tests

### Notes for the reviewer

NA
### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

### CODE REVIEW

**Comment by Amnah199** [comment]
Should we also make truncation optional for BedrockChatGenerators?

**Comment by sjrl** [comment]
> Should we also make truncation optional for BedrockChatGenerators?

I would also be in support of that :)

**Review by julian-risch — CHANGES_REQUESTED** [review]
Looks quite good to me already. Could you please add a small test that checks the behavior when truncate is set to False. Basically a mix of the two existing test cases `test_short_prompt_is_not_truncated(mock_boto3_session)` and `test_long_prompt_is_truncated(mock_boto3_session)` where you have a long prompt and `truncate=False` and then you check that the prompt wasn't truncated.

**Comment by julian-risch** [comment]
Regarding BedrockChatGenerators please create a new issue for that and then we can assign it in one of the next sprints.

**Review by julian-risch — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
