### PR TITLE
chore: Update docstring and type of fuzziness

### PR DESCRIPTION
**Pull request by sjrl**
### Related Issues

- fixes #issue-number

### Proposed Changes:

 
 
Updates the doc string of the fuzziness parameter and the type. Accepts string or int

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

### CODE REVIEW

**Comment by mpangrazzi** [comment]
@sjrl thanks for this! LGTM

**Review by mpangrazzi — APPROVED** [review]

**Comment by sjrl** [comment]
Thanks @mpangrazzi! Would it be possible to get a new release of this integration as well?

**Comment by mpangrazzi** [comment]
@sjrl yes, we just released [integrations/opensearch-v1.2.0](https://github.com/deepset-ai/haystack-core-integrations/tree/main/integrations/opensearch)

**Comment by sjrl** [comment]
Thanks!

**Pull request merged**
