### PR TITLE
docs: update category slug

### PR DESCRIPTION
**Pull request by dfokina**
`category_slug` changed on Readme from Haystack Integrations to Integrations API, which prevented docs from syncing

### CODE REVIEW

**Review by silvanocerza — APPROVED** [review]

**Comment by anakin87** [comment]
@dfokina I just added the docs workflow for Amazon Sagemaker in #439.
Please consider changing it too (if needed)...

**Comment by silvanocerza** [comment]
Disregard the failing tests, it's the `MongoDBAtlasDocumentStore` failing for reasons unrelated to docs.

I'll take care of merging after the rest is green.

**Comment by silvanocerza** [comment]
@ZanSara any idea why the Mongo tests are failing?

**Comment by silvanocerza** [comment]
There are other failures but not related to docs either. I'll merge.

Pinecone has a proper failure seems like, some filter is not working as expected 👉  https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7961556591/job/21733080016?pr=442 

Google AI is failing cause of 500 👉  https://github.com/deepset-ai/haystack-core-integrations/actions/runs/7961556593/job/21733080904?pr=442

**Pull request merged**
