### PR TITLE
feat: bedrock converse

### PR DESCRIPTION
**Pull request by FloRul**
### Related Issues
[#977](https://github.com/deepset-ai/haystack-core-integrations/issues/977)

### Proposed Changes:
Added a new converse generator, some other utility classes have been added to facilitate its use such as ConverseMessage or ToolConfig

### How did you test it?

unit test and manual testing mostly

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

### CODE REVIEW

**Comment by FloRul** [comment]
@silvanocerza  It seems like the AWS region is not assigned in the CI. I had the same issues in my previous PR.

**Comment by silvanocerza** [comment]
@FloRul PR from forks can't have access to repository secrets. 
Those tests should be skipped if the necessary secrets are not found, see [this as an example](https://github.com/deepset-ai/haystack-core-integrations/blob/7cd71f17a3f86a22f74e85db2825f993c597e5b8/integrations/anthropic/tests/test_chat_generator.py#L165-L168).

**Comment by silvanocerza** [comment]
Why do we need a new converse generator? Isn't it akin to a chat generator that we already have? Shouldn't we update that?

It seems like all the abstractions added are extremely similar to existing ones for chat generators. 🤔

**Comment by FloRul** [comment]
> Why do we need a new converse generator? Isn't it akin to a chat generator that we already have? Shouldn't we update that?
> 
> It seems like all the abstractions added are extremely similar to existing ones for chat generators. 🤔

That is a fair point, the thing with the current bedrock chat is that it relies on adpaters, would it be more logic to consider converse its own adapter ? Keeping in mind that aws seems to aim at converse being the main point of entry for bedrock inference api.

**Comment by silvanocerza** [comment]
> That is a fair point, the thing with the current bedrock chat is that it relies on adpaters, would it be more logic to consider converse its own adapter ? Keeping in mind that aws seems to aim at converse being the main point of entry for bedrock inference api.

I would consider converse its own adapter. If AWS goes all in with this kind of common API we can ditch completely the adapter concepts too. That's less code to maintain. :)

Maybe the best approach would be to ditch the adapters for those models that support the new Converse API, that should work right?

**Comment by FloRul** [comment]
The idea behind adding a new generator was because of the standardization, which results in a richer output from the generator as well as facilitating the multimodal integration.
I think trying to put the implementation in the former ChatGenerator would either not be retrocompatible or making it lose all the benefits this implementation tries to provide: easier tool calling, multimodal integration and richer output.

**Comment by silvanocerza** [comment]
We already have a standard and that is the `ChatMessage`. Adding all the classes from `utils.py` goes against that.

This Component will be extremely hard to use in any existing `Pipeline`s in place of other generators also. The `ConverseMessage` is a completely new type that no other Component returns as output nor expects as input. It would be completely isolated.

That's why I'm advocating to use the existing interfaces and types.

**Comment by FloRul** [comment]
Ok @silvanocerza I'll look into that.

**Comment by anakin87** [comment]
Superseded by #1219

**Pull request closed without merging**
