### PR TITLE
Add supabase vectordb

### PR DESCRIPTION
**Pull request by sahusiddharth**
- part of #73 
- Vecs Python Client Integration: The pull request includes the incorporation of the Supabase Vecs Python client into the Haystack codebase.
- Support for Supabase Vector Store: Code modifications have been made to enable Haystack to interact with and utilize the capabilities of the Supabase Vector Store.

### CODE REVIEW

**Comment by julian-risch** [comment]
Hello @sahusiddharth I see you opened this PR and closed the old PR https://github.com/deepset-ai/haystack-core-integrations/pull/189 . Great to see that you added test cases! I have a couple of questions that should help us to review the PR quickly and get it ready for merging soon:
 I saw the the conf test contains credentials. Could you please double check whether that was on purpose? I also noticed that there is no LICENSE.txt file. Did you follow the steps described here to create the new integration: https://github.com/deepset-ai/haystack-core-integrations/tree/add-supabase-vectordb?tab=readme-ov-file#create-a-new-integration ? `SLEEP_TIME` is defined in the conftest.py but it's not used, so I guess you found a way to let the tests pass without it? Did you run the tests locally with the command `hatch run test`?

**Comment by sahusiddharth** [comment]
@julian-risch, 

Q: I saw the the conf test contains credentials. Could you please double check whether that was on purpose?
- It was just for testing, I couldn't figure out a better way

Q: I also noticed that there is no LICENSE.txt file.
- I will add it asap

Q:Did you follow the steps described here to create the new integration?
- yes, but not sequentially I'll double check and let you know when it is done.

Q: SLEEP_TIME is defined in the conftest.py but it's not used, so I guess you found a way to let the tests pass without it?
- I followed the pinecone implementation I don't perfectly understand the purpose of `SLEEP TIME`. 

Q: Did you run the tests locally with the command hatch run test?
- Yes, 3 filter test case are failing and I have asked @masci about it in [discord](https://discord.com/channels/993534733298450452/993534734091157668/threads/1198553794892550236)

**Comment by sahusiddharth** [comment]
```python
def to_dict(self) -> Dict[str, Any]:
        """
        Serializes this store to a dictionary.
        """

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "DocumentStore":
        """
        Deserializes the store from a dictionary.
        """

```

These two functions are missing from the code based on [creating custom document store](https://docs.haystack.deepset.ai/v2.0/docs/creating-custom-document-stores)

**Review by masci — CHANGES_REQUESTED** [review]
Can you update the source layout to the latest convention? You can have a look at the other document stores in this repo, but basically you would have:
```
src/haystack_integrations/document_stores/supabase/__init__.py
src/haystack_integrations/document_stores/supabase/document_store.py
src/haystack_integrations/document_stores/supabase/filters.py
src/haystack_integrations/components/retrievers/supabase/__init__.py
src/haystack_integrations/components/retrievers/supabase/retriever.py
```

**Comment by sahusiddharth** [comment]
on it

**Comment by sahusiddharth** [comment]
hello @masci, about this PR 

- two function `to_dict` and `from_dict` are missing and their test cases are also missing
- 3 errors when running command `hatch run test`
   1. test_or_operator
   2. test_comparision_not_equal_to
   3. test_no_filters

**Comment by masci** [comment]
@sahusiddharth do you want me to take a stab at the `to_dict` and `from_dict` functions?

**Comment by sahusiddharth** [comment]
@masci I won't mind

**Comment by sahusiddharth** [comment]
@masci can I contribute in some way?

**Comment by sahusiddharth** [comment]
@masci any updates?

**Comment by masci** [comment]
Hi @sahusiddharth 
we synced internally and we decided not to add support for Supabase at this time. You can still create an integration you own but we won't merge it to Core, thanks for your work!

**Comment by WeiY** [comment]
@sahusiddharth are you still maintaining the supabase support for haystack? I am interested in how it works? @masci is there any plan to merge the supabase support to haystack officially? Thanks

**Pull request closed without merging**
