### PR TITLE
chore: Cohere namespace change

### PR DESCRIPTION
**Pull request by vblagoje**
### Why:
The changes in this pull request are focused on restructuring and reorganizing the codebase for better modularity and clarity. The modifications include updates to project configuration files, renaming of files and directories, and updating references to match the new structure. These adjustments enhance the maintainability of the code and align with a more standardized project layout.

- part of https://github.com/deepset-ai/haystack-core-integrations/pull/247

### What:
- Updated the `pyproject.toml` file to refer to new package locations and configuration settings.
- Added new `__init__.py` files to define public interfaces for embedders and generators components, ensuring clean imports and namespace management.
- Moved and renamed several `embedders` and `generators` modules to fall under a more descriptive `haystack_integrations` namespace.
- Adjusted test files to reference the renamed modules, ensuring consistency and passing tests.

### How can it be used:
- The `pyproject.toml` updates can be used to accurately reflect dependencies and project configuration for building the wheel.
- The new `__init__.py` files allow users to import classes like `CohereDocumentEmbedder`, `CohereTextEmbedder`, and `CohereGenerator` more intuitively using the updated paths.
- The renamed modules help clarify their purpose and usage within the project, such as:
  ```python
  from haystack_integrations.components.embedders import CohereDocumentEmbedder
  ```

### How did you test it:
- The updates in the test modules, such as `test_cohere_chat_generator.py` and `test_document_embedder.py`
- Additional testing should include running the full suite of unit tests, as well as integration tests to confirm that the new structure doesn't break any existing functionality.

### Notes for the reviewer:
- Ensure that the new structure follows the Python package conventions and does not break any imports elsewhere in the project.
- Verify that all tests, including integration tests not shown in the PR diff, pass after the restructuring.
- Scrutinize the `pyproject.toml` changes to ensure that all necessary configurations are appropriately updated and no essential configurations are omitted.

### CODE REVIEW

**Review by masci — CHANGES_REQUESTED** [review]
Overall looks good, one missing thing, we need an additional `cohere` folder so that the import becomes:
`from haystack_integrations.components.embedders.cohere import CohereDocumentEmbedder`

This is needed because otherwise different integrations might mount generators with the same name under `haystack_integrations.components.embedders`, overwriting each other

**Comment by vblagoje** [comment]
🤦 have another look @masci

**Comment by masci** [comment]
@vblagoje can you remove the `.idea/` folder? :)

**Comment by vblagoje** [comment]
O wow 🤣

**Review by masci — APPROVED** [review]
LGTM Thanks!

**Pull request merged**
