### PR TITLE
feat: Update astradb integration for latest client library

### LINKED ISSUE #1139: 'in' operator with AstraEmbeddingRetriever filters in Haystack
Hi, I am trying to use the 'in' operator with AstraEmbeddingRetriever filters in Haystack  but it does not retrieve any document, operator "==" works. Am I doing something wrong or is it not well implemented yet? I am using the last versions:

```
- haystack-ai = 2.6.1
- astra-haystack = 0.9.3 
```

```
def run_pipeline(self, query: str):
        filters = {
            "operator": "AND",
            "conditions": [
                {"field": "meta.name", "operator": "in", "value": ["programs", "promotions", "plans"]},
            ],
        }
        inputs = {  'embedder':
                        {'text': query},
                    'retriever':
                        {'filters': filters},
                    'ranker':
                        {'query': query},
                  }
        output = self.run(inputs)
        return output
```
This thread is related with issue: https://github.com/deepset-ai/haystack-core-integrations/issues/865

### PR DESCRIPTION
**Pull request by erichare**
### Related Issues

- fixes #1139

### Proposed Changes:

This update modernizes the Astra DB integration to use the latest `astrapy` client library (>=1.5.0) and the associated improvements that come with it, including fixes for filter conditions and criteria as per the issue above.

### How did you test it?

I updated and re-ran all Astra DB pytest tests and confirmed successful execution

### Notes for the reviewer

Please ensure I correctly bumped the version requirement for `astrapy` as this does require `astrapy>=1.5.0`

### Checklist

[x] I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
[x] I have updated the related issue with new insights and changes
[x] I added unit tests and updated the docstrings
[x] I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

### CODE REVIEW

**Comment by davidsbatista** [comment]
Hi @erichare, thanks for this contribution - I've just reverted the `CHANGELOG.md` to the original since the changes are added automatically.

**Review by davidsbatista — APPROVED** [review]

**Comment by erichare** [comment]
> Hi @erichare, thanks for this contribution - I've just reverted the `CHANGELOG.md` to the original since the changes are added automatically.

Thanks! My bad,  missed that it was auto generated. I appreciate it!

**Comment by erichare** [comment]
@davidsbatista Sorry David, I forgot to mention, but would you (or another maintainer) be able to help with releasing a new version of the Astra integration based on this PR? From the README, it sounds like tagging the commit and doing the CI for it needs to be done by a maintainer. Let me know if you need anything else from me for that. Thanks a lot for the help

**Comment by davidsbatista** [comment]
it's done: https://pypi.org/project/astra-haystack/ - I just released it a few minutes ago.

**Comment by erichare** [comment]
Fantastic. Thanks again!!

**Pull request merged**
