### PR TITLE
add openvino generator 

### PR DESCRIPTION
**Pull request by openvino-dev-samples**

### CODE REVIEW

**Comment by vblagoje** [comment]
Hey @OpenVINO-dev-contest this work is solid! Thank you for your contribution. I have consulted with my colleagues internally and we suggest to make this a https://github.com/deepset-ai/haystack-integrations contributions. This means that essentially everything stays the same as in this PR but you maintain it yourself in your repo of choosing. And we'll list it our https://haystack.deepset.ai/integrations as well.

**Comment by OpenVINO-dev-contest** [comment]
hi @vblagoje  you mean this PR will not be merged, right ?

I have open a discussion before this PR, and it said `haystack-core-integrations)` is open for contribution.

https://github.com/deepset-ai/haystack/discussions/7998

**Comment by vblagoje** [comment]
> hi @vblagoje you mean this PR will not be merged, right ?
> 
> I have open a discussion before this PR, and it said `haystack-core-integrations)` is open for contribution.
> 
> [deepset-ai/haystack#7998](https://github.com/deepset-ai/haystack/discussions/7998)

@OpenVINO-dev-contest my colleague most likely didn't know about this decision. Every integration in this repository requires full attention from us in terms of documentation, release cycles, adding new features, maintenance and bug fixes. We are stretched too thin. Noting related to importance of this integration and code quality but mere resources. We have made decision to be really restrictive about new integrations in this repo because we simply can't support it at the high level we have set for ourselves. Hope you understand and issue PR at https://github.com/deepset-ai/haystack-integrations - we'll gladly merge it there and list it on https://haystack.deepset.ai/integrations Everything is pretty much the same in terms of user experience but in this case you maintain the integration yourself.

**Comment by vblagoje** [comment]
Closing, hopefully we'll get an independently maintained OpenVINO integration for Haystack.

**Pull request closed without merging**
