### PR TITLE
[Test/WIP] feat: check compatibility

### PR DESCRIPTION
**Pull request by ArzelaAscoIi**
### Related Issues

- fixes #issue-number

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

### CODE REVIEW

**Comment by silvanocerza** [comment]
We shouldn't do this.

It's a mess that we decided we wanted to avoid completely with Haystack 2 and that's why we have the integrations completely separate.

This is a huge amount of work and creates a huge amount of conflicts and problems that we can't tackle in any way.

**Comment by wochinge** [comment]
> It's a mess that we decided we wanted to avoid completely with Haystack 2 and that's why we have the integrations completely separate.

Fair point. However, when we talked to @shadeMe suggested otherwise. The test seems like a pretty simple way to at least be aware of conflicts.

**Comment by wochinge** [comment]
@ArzelaAscoIi Talked to Madeesh about this. Let's try it out in our pipeline-images repo. Depending on whether there is any problem in the first place, we can reevaluate what the best way forward is (e.g. if there is a simple maintainable fix or if we need to change our approach for building the images). 

Based on the experience in our repository we can then probably also give better input on how much maintenance effort a similar check in this repository would be.

**Comment by ArzelaAscoIi** [comment]
Sure! Sounds good

**Pull request closed without merging**
