### PR TITLE
Add the Cohere client name to cohere requests 

### PR DESCRIPTION
**Pull request by BeatrixCohere**
Adding the client name to Cohere to support debugging and tracing of requests

### CODE REVIEW

**Review by shadeMe — APPROVED** [review]
Thanks for the PR! Could you please sign the CLA? :)

**Comment by shadeMe** [comment]
Thanks for signing the CLA! I'll get it merged once the test are fixed.

**Comment by BeatrixCohere** [comment]
> Thanks for signing the CLA! I'll get it merged once the test are fixed.

For the tests what is the expectation for the API keys, do you have a test API key?

**Comment by shadeMe** [comment]
> For the tests what is the expectation for the API keys, do you have a test API key?

I think the failures are due to the lints? We run a nightly test with our CI API key, so this PR will be fine to merge as long as the changes were tested locally (with a valid API).

**Pull request merged**
