### PR TITLE
add Fastembed Embeddings integration

### PR DESCRIPTION
**Pull request by nickprock**
This is the first version about Fastembed integration.
I developed tests and passed all.
I hope you appreciate.
Waiting for your feedback.

PR related to issue #358 
@anakin87

### CODE REVIEW

**Comment by anakin87** [comment]
Hey! Can you create a GitHub workflow [here](https://github.com/deepset-ai/haystack-core-integrations/tree/main/.github/workflows)?

You can take one of the other workflows (instructor_embedders.yml) as an example.
This will make tests run once a PR is submitted.

**Comment by anakin87** [comment]
I'll try to fix the workflow...

**Comment by anakin87** [comment]
@nickprock now all should be set up.
- Tests pass
- Lint is failing

If you install hatch, it should be also easy to run linting and other stuff in your machine without the need to create a venv.
For example, `hatch run lint:all` should work.

**Comment by nickprock** [comment]
> @nickprock now all should be set up.
> 
>     * Tests pass
> 
>     * Lint is failing
> 
> 
> If you install hatch, it should be also easy to run linting and other stuff in your machine without the need to create a venv. For example, `hatch run lint:all` should work.

should, but don't work :smile: 
the stranger thing is that for the test it works fine

**Comment by anakin87** [comment]
Sorry... We should reintroduce linting (removed along with python 3.9).

The fixes should not be hard. (If they are not reasonable, we can skip some of them.)

**Comment by nickprock** [comment]
Ok, I will try during the weekend.

**Comment by anakin87** [comment]
If you encounter problems, ping me and I will help!

**Comment by anakin87** [comment]
@nickprock I have been trying to solve the problems of ruff linting and have somewhat succeeded.
Now you should run black.

**Comment by nickprock** [comment]
> @nickprock I have been trying to solve the problems of ruff linting and have somewhat succeeded. Now you should run black.

Thanks @anakin87 I'm going to run black in the evening or tomorrow.

**Review by anakin87 — APPROVED** [review]
:guitar:

**Pull request merged**
