### PR TITLE
fix: from numpy float to float

### PR DESCRIPTION
**Pull request by nickprock**
To use the library into pipeline I must change the type of elements in mebeddings from numpy.float to float.

related to issue #358

### CODE REVIEW

**Comment by nickprock** [comment]
at the moment I can't fix it, I thought it was more immediate, I will work on it as soon as I can

**Comment by nickprock** [comment]
*"I put on a colored patch"* (we say in Italy)

**Comment by anakin87** [comment]
Changing the backend should do the trick :smiley:

**Review by anakin87 — APPROVED** [review]

**Comment by nickprock** [comment]
> Changing the backend should do the trick :smiley: 

I didn't have the courage to touch it from the GitHub online editor. 😅

**Pull request merged**
