### PR TITLE
feat: MongoDB Atlas keyword search

### LINKED ISSUE #872: Full-text MongoDBAtlas Retriever
Hello! Thank you for your work on the Haystack integrations, they rock 🤘

**Is your feature request related to a problem? Please describe.**
For the moment there is only a `MongoDBAtlasEmbeddingRetriever` available, which blocks hybrid search on Haystack using MongoDB Atlas as a document store backend.

**Describe the solution you'd like**
Ideally, `MongoDBAtlasDocumentStore` class would be incremented with a `_fulltext_retrieval()` function (+ additional needed functions/properties) that would be called by a new `MongoDBAtlasFullTextRetriever`. This would return the results of a search with the standard MongoDB Atlas query API (using `$search`, as far as I understand).

**Describe alternatives you've considered**
Currently, the alternatives would be (1) to not use hybrid search at all, relying only on semantic search, or (2) hacking together an implementation of a full-text retriever by patching `MongoDBAtlasDocumentStore` and creating a `MongoDBAtlasFullTextRetriever`. None of these are ideal.

**Additional context**
N/A

Thanks for your attention reading this, and hope you consider it :)

### PR DESCRIPTION
**Pull request by kanenorman**
### Related Issues

- fixes #872 
- please review in favor of #1140 

### Proposed Changes:
Added `MongoDBAtlasDocumentStore._fulltext_retrieval()` and the corresponding `MongoDBAtlasFullTextRetriever` component, enabling users to leverage MongoDB Atlas's full-text search capabilities.

### How did you test it?
- Updated existing test to handle new init parameter `full_text_search_index`
- Added test for `MongoDBAtlasFullTextRetriever` component to `test_retriever.py`

I did not implement a test for full-text retrieval. Similar to `test_embedding_retrieval.py`, it would likely be more secure and maintainable for a member of the Haystack team to write the test for a collection created in Haystack's MongoDB Atlas cluster, specifically in a file called `test_fulltext_retrieval.py.`. (I would also be willing to write test if that is preferred).

### Notes for the reviewer
In `MongoDBAtlasDocumentStore._fulltext_retrieval()`, filters are currently passed directly to the `$match` stage, similar to how [Langchain implements this behavior](https://github.com/langchain-ai/langchain-mongodb/blob/8514d09c952a5f78363225ae034c33c1ad866717/libs/mongodb/langchain_mongodb/pipelines.py#L44). While this approach works, it is not optimal for performance, as outlined in the [MongoDB Atlas documentation](https://www.mongodb.com/docs/atlas/atlas-search/performance/query-performance/#avoid--match-after--search). A more efficient solution would involve adding a `filter` clause to the `compound` operator. However, this requires additional work since the filter syntax used in the `$match` stage is not directly compatible with the `$filter` clause. Implementing this would require writing a new helper function, `_normalize_compound_filter`, to convert Haystack filter syntax into the format understood by MongoDB’s compound filter. Given that this would significantly expand the size & scope of this PR, I believe it is more appropriate to address this enhancement in a separate PR.

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

### CODE REVIEW

**Comment by kanenorman** [comment]
I'm encountering a peculiar configuration error in CI when running this line of code:

```python
connection: MongoClient = MongoClient(
    os.environ["MONGO_CONNECTION_STRING"], 
    driver=DriverInfo(name="MongoDBAtlasHaystackIntegration")
)
```

The error is as follows:

```python
/home/runner/.local/share/hatch/env/virtual/mongodb-atlas-haystack/BNcyCByD/mongodb-atlas-haystack/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py:797: in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

hosts = '', default_port = 27017

    def split_hosts(hosts: str, default_port: Optional[int] = DEFAULT_PORT) -> list[_Address]:
        """Takes a string of the form host1[:port],host2[:port]...
        Splits it into (host, port) tuples. If [:port] isn't present, the
        default_port is used.
        ...
        """
        nodes = []
        for entity in hosts.split(","):
            if not entity:
>               raise ConfigurationError("Empty host (or extra comma in host list).")
E               pymongo.errors.ConfigurationError: Empty host (or extra comma in host list).

/home/runner/.local/share/hatch/env/virtual/mongodb-atlas-haystack/BNcyCByD/mongodb-atlas-haystack/lib/python3.10/site-packages/pymongo/uri_parser.py:392: ConfigurationError
```

This issue occurs only on Mac/Linux CI but not on Windows. Curiously, I cannot reproduce the failure locally on my Mac. I'll continue investigating the root cause of this inconsistency in the CI environment.

**Comment by anakin87** [comment]
Hey @kanenorman, thanks for the contribution and sorry for the delay...

I will try to have a look in the next few days!

**Comment by vblagoje** [comment]
@kanenorman my colleague @mpangrazzi and I will take over the review of this PR. 

This PR already looks good. Before we dive into details, would you please:
- add test_fulltext_retrieval.py as you suggested
- if possible a new example for this feature in examples dir

Can we somehow use both text-search and vector indices? If so an example of both retrieval setups for our users would be great. If this is possible perhaps @mpangrazzi and I can work on this example. 

Regarding CI - you are right. Let me see internally what we can do here short of migrating your branch to our main fork and two of us doing the final polishing, checks and the final integration.

**Comment by vblagoje** [comment]
Yes - it would be nice for the community to see this example and for all of us to easily verify we nailed this one. 🙏

**Comment by kanenorman** [comment]
@vblagoje - I've added `integrations/mongodb_atlas/examples/hybrid_retrieval.py` to demonstrate how `MongoDBAtlasFullTextRetriever` and `MongoDBAtlasEmbeddingRetriever` can be used together to create a hybrid retrieval pipeline.

For the full-text search test in `test_fulltext_retrieval.py`, I completed the following setup:

1. Created the `full_text_index` in MongoDB atlas UI
2. Inserted test documents into the document store:
```python
docs = [
    Document(
        content="The quick brown fox chased the dog",
        meta={"meta_field": "right_value"}
    ),
    Document(
        content="The fox was brown",
        meta={"meta_field": "right_value"}
     ),
    Document(content="The lazy dog"),
    Document(content="fox fox fox"),
]
document_store.write_documents(docs)
```

3. Added a synonym mapping for testing:
```json
{"mappingType":"equivalent","synonyms":["fox","reynard"]}
```

Please let me know if you need any additional details or assistance setting up the test environment.

**Comment by mpangrazzi** [comment]
@kanenorman thanks for your work! 🙏 I'll review with @vblagoje soon!

**Comment by mpangrazzi** [comment]
Hi @kanenorman! We've reviewed the code and opened [this](https://github.com/deepset-ai/haystack-core-integrations/pull/1228) (on our branches we have no secrets issue).

We updated [test_fulltext_retrieval.py](https://github.com/deepset-ai/haystack-core-integrations/blob/mongodb-keyword-search/integrations/mongodb_atlas/tests/test_fulltext_retrieval.py) according to your comment, but it seems that some tests are still failing (see [here](https://github.com/deepset-ai/haystack-core-integrations/actions/runs/12144194688/job/33862940142?pr=1228)). 

Are they running correctly on your side? How have you created the `full_text_index`? Thanks!

**Comment by kanenorman** [comment]
Hi, @mpangrazzi. I apologize for not including this in my previous comment.

This is the index that I created where `fox_synonyms` is a collection containing the synonym mapping I mentioned in the previous comment. The test passed on my local machine when I ran with these configurations. please let me know if there are further issues.

```
{
  "mappings": {
    "dynamic": false,
    "fields": {
      "content": [
        {
          "type": "string"
        }
      ]
    }
  },
  "synonyms": [
    {
      "analyzer": "lucene.standard",
      "name": "synonym_mapping",
      "source": {
        "collection": "fox_synonyms"
      }
    }
  ]
}
```

**Comment by mpangrazzi** [comment]
@kanenorman Thanks for your answer! We have everything working correctly [here](https://github.com/deepset-ai/haystack-core-integrations/pull/1228). We'll do a final review soon.

**Comment by mpangrazzi** [comment]
@kanenorman Closing this since https://github.com/deepset-ai/haystack-core-integrations/pull/1228 has been merged!

**Pull request closed without merging**
