### PR TITLE
fix: remove support for native filters from Qdrant integration

### LINKED ISSUE #1093: Remove support for native filters in QdrantDocumentStore
## Summary and motivation

Currently the [`filter_documents`](https://github.com/deepset-ai/haystack-core-integrations/blob/c0750ec01c8689e0d86e193223f3a2d807a3a32b/integrations/qdrant/src/haystack_integrations/document_stores/qdrant/document_store.py#L309) method in `QdrantDocumentStore` accepts filters in Qdrant syntax. As other integrations do not support legacy or native filters, this method should accept only haystack filters.

### PR DESCRIPTION
**Pull request by Amnah199**
### Related Issues

- fixes #1093 

### Proposed Changes:

Update the Qdrant document store and retrievers to remove support for Qdrant native filters. Only haystack filters can be provided as is the case in other integrations.

### How did you test it?

Ran the existing tests

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

### CODE REVIEW

**Comment by anakin87** [comment]
It seems to me that we are not removing support for our legacy filters, but for Qdrant native filters.
They were introduced in https://github.com/deepset-ai/haystack-core-integrations/pull/692.

**Comment by Amnah199** [comment]
@silvanocerza we would like your opinion about this PR. Stefano believes we should keep the support for native filters in Qdrant as some users rely on it. But I do not know of any other integrations that support native filters, so this will be an exception. Wdyt?

**Comment by silvanocerza** [comment]
I think we can keep them, ti gives more flexibility to users of the Document Store to create custom retrievers and what not.

**Comment by Amnah199** [comment]
Closing this PR as we have decided not to proceed with merging it.

**Pull request closed without merging**
