### PR TITLE
chore: Update unstructured API endpoint

### PR DESCRIPTION
**Pull request by vblagoje**
- Update Unstructured API endpoint

### CODE REVIEW

**Comment by vblagoje** [comment]
Today while playing with `UnstructuredFileConverter` component I discovered the current endpoint didn't work and has changed to a new one. After setting new endpoint everything started to work again

**Review by davidsbatista — APPROVED** [review]

**Comment by vblagoje** [comment]
Let's have @anakin87 confirm this - he has more context

**Review by anakin87 — APPROVED** [review]
Ok for me.

Can you check if we need to update docs/integration page?

**Comment by vblagoje** [comment]
Upon reading our docs https://docs.haystack.deepset.ai/docs/unstructuredfileconverter I realized that everything is working as expected. The key sentence is "For the Free Unstructured API, the API URL is https://api.unstructured.io/general/v0/general. For the Unstructured Serverless API, find your unique API URL in your Unstructured account." 

So what was happening is - when I started using unstructured, not being aware of these subscription tiers, I used serveless API feature chunking by similarity and then API was failing with some strange errors leading me to conclude that something is off. I then saw that API endpoint is different on my unstructured homepage:
Screenshot 2024-09-12 at 09 49 05


As you can see above it is https://api.unstructuredapp.io/general/v0/general

But this endpoint is only for paid Unstructured features, i.e. their Serverless API tier.

This is the most confusing service offering I've ever seen. 
@dfokina can we somehow explain this gotchas even better on our https://docs.haystack.deepset.ai/docs/unstructuredfileconverter docs page. We also need to add `pip install unstructured-fileconverter-haystack` to that page.

Closing this issue now.

**Comment by vblagoje** [comment]
Actually @dfokina I'll do this and you approve it (or not :-))

**Pull request closed without merging**
