### PR TITLE
Add Ollama Text Embedder

### PR DESCRIPTION
**Pull request by AlistairLR112**
Very simple implementation

### CODE REVIEW

**Comment by anakin87** [comment]
Hey @AlistairLR112...

We recently changed the project structure in #216.
We did this to allow better imports of haystack-core-integrations: e.g.,
`from haystack_integrations.components.generators.ollama import OllamaChatGenerator`

Please update this PR to reflect this.
When ready, put the PR in the "ready for review" status and ping me. :raised_hands:

**Comment by AlistairLR112** [comment]
Do you want ```haystack_integrations.components.embeddings.ollama import OllamaTextEmbedder``` ?

**Comment by anakin87** [comment]
It should become `from haystack_integrations.components.embedders.ollama import OllamaTextEmbedder`.

**Comment by AlistairLR112** [comment]
Closing - opening with new branch https://github.com/deepset-ai/haystack-core-integrations/pull/252

**Pull request closed without merging**
